### ISSUE TITLE
Result 组件 img 属性 定制大小的问题请教

### ISSUE THREAD

**Issue by junmaqiang** [ant-design/ant-design-mobile#1138]
![Uploading 22.png…]()

**Comment by paranoidjk** [comment]
阅读issue模版

**Comment by junmaqiang** [comment]
![22](https://cloud.githubusercontent.com/assets/1819457/24985703/7eee8108-2028-11e7-9038-fa840b45a973.png)

**Comment by silentcloud** [comment]
@junmaqiang 用 css 样式覆盖即可 
```css
.am-result .am-result-pic {
    width:
    height:
}
```
