### ISSUE TITLE
关于 九宫格 Grid 在ios8.*系统中flex显示的bug

### ISSUE THREAD

**Issue by guyuleo** [ant-design/ant-design-mobile#1214]
### Version
1.0.7

### Environment
IOS  8.*

### Reproduction link
[http://blm.test.otosaas.com/chongzhi](http://blm.test.otosaas.com/chongzhi)

### Steps to reproduce
载入完后，显示问题，原本应该是九宫格显示，可是变成一行显示，并且可左右滑动。
![wechatimg2](https://cloud.githubusercontent.com/assets/18536084/25428264/e9328648-2aa7-11e7-87cf-05538d4b8fab.jpeg)
![wechatimg1](https://cloud.githubusercontent.com/assets/18536084/25428221/c008762e-2aa7-11e7-8746-40d3b5b2202a.jpeg)

### What is expected?
九宫格显示
![wechatimg2](https://cloud.githubusercontent.com/assets/18536084/25428338/21d7785a-2aa8-11e7-9e4a-feaedb88e669.jpeg)

### What is actually happening?
一行显示，可以左右滑动。

**Comment by paranoidjk** [comment]
@warmhug flex-wrap 在ios8 有兼容性问题吗？

**Comment by paranoidjk** [comment]
@gutenye 请升级到最新版 1.1.0 试试，看了下你的demo少了 `-webkit-flex-wrap` 样式

**Comment by paranoidjk** [comment]
@gutenye 

- 这是你的样式
```css
.am-flexbox.am-flexbox-wrap {
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}
```

- 这是antd-mobile的样式
```css
.am-flexbox.am-flexbox-wrap {
  -webkit-flex-wrap: wrap;
      -ms-flex-wrap: wrap;
          flex-wrap: wrap;
}
```

应该与你项目的构建环境有关： https://github.com/postcss/autoprefixer/issues/766
