### ISSUE TITLE
implement of 1px line

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design-mobile#1270]
right now antd-mobile use [viewport scale](https://github.com/ant-design/ant-design-mobile/blob/master/components/style/mixins.less#L10) to implement 1px line.

This actually made our [viewport scripts](https://github.com/ant-design/ant-design-mobile/wiki/antd-mobile-0.8-%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC%E3%80%8C%E9%AB%98%E6%B8%85%E3%80%8D%E6%96%B9%E6%A1%88%E8%AE%BE%E7%BD%AE) not optional. But in some situations，such as use with canvas or map, the viewport can not be scale.

What if others ways? I see there are some other ways left in our code.

- [background-image + linear-gradient](https://github.com/ant-design/ant-design-mobile/blob/master/components/style/mixins.less#L161)
- [scaleY](https://github.com/ant-design/ant-design-mobile/blob/master/components/style/mixins.less#L186)

**Comment by paranoidjk** [comment]
cc @pingan1927 @warmhug

**Comment by paranoidjk** [comment]
I prefer not rely on viewport scale, eg:
```less
.border-1px-scale {
  position: relative;
  :before { 
      content: ''; 
      position: absolute; 
      width: 200%; 
      height: 200%; 
      border: 1px solid #000; 
      transform-origin: 0 0; 
      transform: scale(0.5, 0.5); 
      box-sizing: border-box; 
  }
}
```
