### ISSUE TITLE
wrap when the length of the tabpane title too long

### ISSUE THREAD

**Issue by alanwei0** [ant-design/ant-design-mobile#2200]

**Comment by alanwei0** [comment]
as follows：
![image](https://user-images.githubusercontent.com/3991105/34409690-52589bba-ec06-11e7-9ebf-c9bb626efa1e.png)

i think should prevent wrap in tabpane's title, for example: 
```css
.am-tabs-default-bar-top .am-tabs-default-bar-tab {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
