### ISSUE TITLE
tabBar组件有bug

### ISSUE THREAD

**Issue by jisao** [ant-design/ant-design-mobile#2413]
tabBar组件里面的子页面在上下滑动的时候会卡顿不流畅，手指划多少距离页面就走多少距离。
如果在页面标签上加上-webkit-overflow-scrolling : touch;这样看似解决了问题，但是又会出现新的问题，会出现在滑到顶部或者底部的时候，页面会突然滑不动，要手指点一下页面，然后再滑动才会有效果

**Comment by zhang740** [comment]
检查外层是否有fixed

**Comment by jisao** [comment]
[www.ninilive.top](url) 用手机打开此DEMO，就会发现问题

**Comment by zhang740** [comment]
android Chrome & wechat 未复现，请提供完整环境信息

**Comment by jisao** [comment]
我是用苹果手机测试的，ios系统环境下不行，你可以测试下

**Comment by jisao** [comment]
等待回复中！

**Comment by lusanshao** [comment]
是的,iPhone下会出现这样的问题,我也遇到了

**Comment by zhang740** [comment]
```css
.am-tabs-pane-wrap {
  -webkit-overflow-scrolling: touch;
}
```
@jisao @lusanshao

**Comment by mogazheng** [comment]
同样遇到这个问题

**Comment by mogazheng** [comment]
外层有用fixed，问题和楼主的描述一模一样，容器设置-webkit-overflow-scrolling : touch；滑动到顶部或者底部之后，放开手，重新尝试滑动就动不了了。

**Comment by mogazheng** [comment]
@jisao 我尝试了多次，发现是下拉滑动到顶部之后，放开，这个时候上拉滑动是可以的。如果下拉滑动到顶部之后，放开，再下拉，之后就动不了了。

**Comment by DasonCheng** [comment]
```css
*{
  -webkit-overflow-scrolling: touch;
}
```
fixed
