### ISSUE TITLE
A Question About Flex Component Style

### ISSUE THREAD

**Issue by targeral** [ant-design/ant-design-mobile#2462]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.8

### Environment
 Not related to the environment

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/master/components/flex/style/index.less](https://github.com/ant-design/ant-design-mobile/blob/master/components/flex/style/index.less)

### Steps to reproduce
the style.less In Flex Component:
``` less
  &&-align-content-start {
    align-content: flex-start;
  }

  &&-align-content-end {
    align-items: flex-end;
  }

  &&-align-content-center {
    align-items: center;
  }
```
Why ‘&&-align-content-end’ class use ‘align-item’?

### What is expected?
I think use ‘align-content’

### What is actually happening?
``` less
  &&-align-content-start {
    align-content: flex-start;
  }

  &&-align-content-end {
    align-items: flex-end;
  }

  &&-align-content-center {
    align-items: center;
  }
```
