### ISSUE TITLE
请问怎样修改antd-mobile中封装好的组件的样式？比如想要修改Picker组件右侧的文字多出内容不是以省略号形式隐藏

### ISSUE THREAD

**Issue by liuyuemozhu** [ant-design/ant-design-mobile#2853]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd-mobile中Picker组件很好用，但是需要修改下样式，右侧的文字内容过长，但是想要把内容全部都显示出来，看了下，可以修改其中的.am-list-extra样式就可以实现，请问该怎样修改一个组件中内部的样式？

### What does the proposed API look like?
无

**Comment by liuyuemozhu** [comment]
求解答

**Comment by likezero** [comment]
查看一下DOM结构，进行样式覆盖。

**Comment by pkaq** [comment]
@liuyuemozhu

> 求解答

```less
:global{
  .am-list-item .am-list-line .am-list-content{
    -webkit-flex-basis: auto !important;
    flex-basis: auto !important;
    width: 32% !important;
  }
  .am-list-item .am-list-line .am-list-extra {
    -webkit-flex-basis: auto !important;
    flex-basis: auto !important;
    width: 68% !important;
  }
}
```
把这个贴到你的global里去
