### ISSUE TITLE
ListView 如何设置Body的背景颜色？

### ISSUE THREAD

**Issue by charminghiker** [ant-design/ant-design-mobile#3832]
![image](https://user-images.githubusercontent.com/34738577/123073613-24cc4500-d449-11eb-9c10-7145ce104f5a.png)
如图中红框内的背景色，怎么设置

**Comment by wanghaida** [comment]
1. 可以给 `List` 组件增加 `className` 或者 `style` 去调整
2. 增加样式强制覆盖
```less
.wrap {
    :global(.adm-list) {
        background-color: transparent;
    }
}
```
