### ISSUE TITLE
List组件自带元素重写样式问题

### ISSUE THREAD

**Issue by 1996xuhuanfeng** [ant-design/ant-design-mobile#4569]
### Version of antd-mobile

5.0.0-rc.3

### What happened?

如果在less 样式文件中有如下重写组件自带元素的样式

```less
.adm-list-inner {
      margin-bottom: unset;
     .selectItem {
        height: 0.6rem;
        width: 96%;
        border: none;
        background-color: unset;
      }
}
```

浏览器模拟手机浏览无问题，在移动端浏览器元素adm-list-inner内的样式会失效，
