### ISSUE TITLE
CSS 变量的 patch 方案

### ISSUE THREAD

**Issue by awmleer** [ant-design/ant-design-mobile#5173]
### Description

在某些情况下，需要兼容到 iOS 9，而 iOS 9.0 9.1 9.2 是完全不支持 CSS 变量的，为了能够兼容这些特殊环境，或许可以通过一套特殊的 patch 代码来实现

TBD flag 先记在这里，具体方案还在考虑

**Comment by awmleer** [comment]
### 方案一

直接在项目中对每个组件提供一份 xxx.patch.css，业务项目需要兼容 iOS 9 的话，就手动引入对应组件的 xxx.patch.css
如果引入了 x.patch.css，就会丧失所有 CSS 变量的能力，不可以兼得

优点：

1. 方案简单，相对来说不那么黑

缺点：

1. 需要手工维护，特别是后面如果 CSS 变量多起来了，工作量应该会很大
2. 每次更新之后很难做自动化的测试和验证

**Comment by Dunqing** [comment]
第一种方案，借助[postcss插件](https://github.com/MadLittleMods/postcss-css-variables#using-variables-custom-properties-with-var)应该可以做到无需手工维护吧

**Comment by awmleer** [comment]
> 第一种方案，借助[postcss插件](https://github.com/MadLittleMods/postcss-css-variables#using-variables-custom-properties-with-var)应该可以做到无需手工维护吧

看起来的确满足这个场景的需求 👍👍👍 我回头试试

**Comment by awmleer** [comment]
试了一下 postcss-css-variables，看起来有些情况还是处理不了的：

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/16526078/168758293-0d593a8b-b92f-413e-8e2e-d01322dbfcc7.png">

**Comment by awmleer** [comment]
```css
:root {
  --adm-color-primary: #1677ff;
  --adm-color-success: #00b578;
  --adm-color-warning: #ff8f1f;
  --adm-color-danger: #ff3141;
  --adm-color-white: #ffffff;
  --adm-color-weak: #999999;
  --adm-color-light: #cccccc;
  --adm-border-color: #eeeeee;
  --adm-font-size-main: 13px;
  --adm-color-text: #333333;
  --adm-hd: 1;
  --adm-font-family: -apple-system, blinkmacsystemfont, 'Helvetica Neue',
    helvetica, segoe ui, arial, roboto, 'PingFang SC', 'miui',
    'Hiragino Sans GB', 'Microsoft Yahei', sans-serif;
}

.adm-avatar {
  --size: var(--adm-avatar-size, 44px);
  --border-radius: var(--adm-avatar-border-radius, 4px);
  border-radius: var(--border-radius);
}
.adm-avatar.adm-image {
  --width: var(--size);
  --height: var(--size);
}
.adm-avatar-fallback {
  height: 100%;
  width: 100%;
  display: block;
}
```
