### ISSUE TITLE
Picker 在暗黑模式下样式仍展示白色

### ISSUE THREAD

**Issue by a145789** [ant-design/ant-design-mobile#5374]
### Version of antd-mobile

v5.15.1

### What happened?

![image](https://user-images.githubusercontent.com/37403253/174963499-2d9b026b-4aa5-4233-be43-bae5584b9bde.png)
查到 .adm-picker-view 类的bg 是 `--adm-color-white`
```css
.adm-picker-view {
    --height: 240px;
    --item-height: 34px;
    --item-font-size: var(--adm-font-size-8);
    height: var(--height);
    width: 100%;
    display: flex;
    position: relative;
    overflow: hidden;
    background: var(--adm-color-white);
}
```

但是修改为 `var(--adm-color-background)` ，样式更奇怪了

![image](https://user-images.githubusercontent.com/37403253/174963974-eeec8566-8fa9-4d0c-86bf-0c600a9226c3.png)

应该是 `adm-picker-view-mask` 类下的问题

> by the way：感觉为整个文档添加一个切换暗黑模式的按钮可能对开发者体验会更好点，希望 antd mobile 越来越好
