### ISSUE TITLE
[FloatingPanel] 展开后 header 与 content 可能存在间隙

### ISSUE THREAD

**Issue by IronKinoko** [ant-design/ant-design-mobile#5538]
### Version of antd-mobile

latest

### Operating system and its version

iOS

### Sandbox to reproduce

https://codesandbox.io/s/pensive-cohen-oik98m?file=/src/App.tsx

### What happened?

当背景色不是白色的时候，移动时很明显能看到 header 与 content 存在间隙

设置 content CSS 修复
```css
.adm-floating-panel-content {
  position: relative;
  top: -1px;
}
```

如果觉得没啥问题，我就提交 pr
