### ISSUE TITLE
Loading Button那个loading图标不会转

### ISSUE THREAD

**Issue by zhaoyao91** [ant-design/ant-design-mobile#604]
如图，这个图标就一直这样，并不像demo一样一直转
![image](https://cloud.githubusercontent.com/assets/3808838/20826892/25970b66-b8a9-11e6-9c48-317b3265d9ee.png)

**Comment by silentcloud** [comment]
@zhaoyao92 

```css
.anticon-loading:before {
    display: inline-block;
    -webkit-animation: loadingCircle 1s infinite linear;
    animation: loadingCircle 1s infinite linear;
    content: "\E6A1";
}
```
看哈 css 有这段么？
